version: "3.4"

services:
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./referencial/django-produtos:/django"
      - "./referencial/fastapi-produtos:/fastapi"
    ports:
      - "8000:8000"
      - "4000:4000"
