FROM python:3.12

# DJANGO 

RUN python -m venv ./venv
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /django

COPY ./referencial/django-produtos/ .

RUN /venv/bin/pip install -r requirements.txt

ENTRYPOINT [ "/entrypoint.sh" ]