FROM python:3.12

# DJANGO 

RUN python -m venv ./venv

WORKDIR /fastapi

COPY ./referencial/fastapi-produtos/requirements.txt .

RUN /venv/bin/pip install -r requirements.txt

CMD ["/venv/bin/uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "4000"]