## docker exec -it mysql-db-1  mysql -h db -u root -p
version: '3'
services:
  db:
    image: mysql
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: meudb
      MYSQL_ROOT_PASSWORD: admin
      # MYSQL_USER: root
      # MYSQL_RANDOM_ROOT_PASSWORD: true
      # MYSQL_ALLOW_EMPTY_PASSWORD: true
  
    ports:
      - "3306:3306"
    volumes:
      - /data:/var/lib/mysql


  